<a href="https://colab.research.google.com/github/patidarparagi286-svg/machine-learning-concepts/blob/main/cgpa_placement(classi).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [ ]:
from google.colab import files
uploaded= files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

Saving cgpa_placement.csv to cgpa_placement (1).csv

In [ ]:
df.head()

   cgpa placement
0  8.38       Yes
1  7.51       Yes
2  8.70       Yes
3  4.71        No
4  4.02        No

In [ ]:
df.tail()

     cgpa placement
195  5.23        No
196  7.51       Yes
197  9.13       Yes
198  4.41        No
199  4.94        No

In [ ]:
df.sample()

     cgpa placement
149  7.18       Yes

In [ ]:
df.isnull().sum()

cgpa         0
placement    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(33)

In [ ]:
df.shape

(200, 2)

In [ ]:
df.describe()

             cgpa
count  200.000000
mean     6.904950
std      1.653187
min      4.020000
25%      5.525000
50%      6.990000
75%      8.290000
max      9.760000

In [ ]:
X=df[["cgpa"]]        #x=alwyas in data frame format (represent in 2d array )
y=df["placement"]     #y=series

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
le=LabelEncoder()
y_encoded=le.fit_transform(y)

In [ ]:
y

0      Yes
1      Yes
2      Yes
3       No
4       No
      ...
195     No
196    Yes
197    Yes
198     No
199     No
Name: placement, Length: 200, dtype: object

In [ ]:
y_encoded

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y_encoded,test_size=0.2,random_state=42)

In [ ]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
X_test

     cgpa
95   5.02
15   5.16
30   8.98
158  8.47
128  8.75
115  4.33
69   5.56
170  8.53
174  5.10
45   5.05
66   7.10
182  4.84
165  8.67
78   4.09
186  7.30
177  7.27
56   6.89
152  8.32
82   7.87
68   7.33
124  9.20
16   7.25
148  9.00
93   9.66
65   5.62
60   5.77
84   6.69
67   4.73
125  8.03
132  9.16
9    8.86
18   7.93
55   9.28
75   6.42
150  6.07
104  4.23
135  5.09
137  4.75
164  8.00
76   7.56

In [ ]:
y_test

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
y_pred

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
result= accuracy_score(y_test,y_pred)
print(result)

1.0

In [ ]:
cgpa=float(input("enter your cgpa:"))
result=model.predict([[cgpa]])
if result==1:
  print("you will be placed")
else:
  print("Sorry.., you will not be placed")

enter your cgpa:7.7
you will be placed

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(