<a href="https://colab.research.google.com/github/patidarparagi286-svg/machine-learning-concepts/blob/main/Decision_tree_with_homeprice_update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded= files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

Saving homeprices_updated.csv to homeprices_updated (1).csv

In [ ]:
df.head()

   area  bedrooms  age   price  sales
0  2600         3   20  550000      1
1  3000         4   15  565000      0
2  3200         4   18  610000      1
3  3600         3   30  595000      1
4  4000         5    8  760000      0

In [ ]:
df.sample()

     area  bedrooms  age   price  sales
176  4419         4   23  910314      0

In [ ]:
df.shape

(500, 5)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      500 non-null    int64
 1   bedrooms  500 non-null    int64
 2   age       500 non-null    int64
 3   price     500 non-null    int64
 4   sales     500 non-null    int64
dtypes: int64(5)
memory usage: 19.7 KB

In [ ]:
df.isnull().sum()

area        0
bedrooms    0
age         0
price       0
sales       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
X=df.drop(columns="sales")
y=df['sales']

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('scale', StandardScaler(), X.columns)    #scale all feature columns
    ],
    remainder="drop"   #drop all other columns not listed in transformers
  )

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

In [ ]:
#model : decision tree(infomation gain method = entropy(default) , gini)
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=2,
    random_state=42
)

In [ ]:
#Pipeline : preprocessing + maodel
pipe = Pipeline(steps=[
    ('prep', preprocessor),
    ('model', model)
])

In [ ]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('scale', StandardScaler(),
                                                  Index(['area', 'bedrooms', 'age', 'price'], dtype='object'))])),
                ('model',
                 DecisionTreeClassifier(max_depth=2, random_state=42))])

In [ ]:
y_pred = pipe.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.475