<a href="https://colab.research.google.com/github/patidarparagi286-svg/machine-learning-concepts/blob/main/tips_one_hot_encode(regr).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded= files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

Saving tips.csv to tips.csv

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df.shape

(244, 7)

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df.min()

total_bill      3.07
tip              1.0
sex           Female
smoker            No
day              Fri
time          Dinner
size               1
dtype: object

In [ ]:
df.max()

total_bill    50.81
tip            10.0
sex            Male
smoker          Yes
day            Thur
time          Lunch
size              6
dtype: object

In [ ]:
df_encoded = pd.get_dummies(df, columns=['sex', 'smoker', 'day', 'time'])
#df_encoded = pd.get_dummies(df, columns=['sex', 'smoker', 'day', 'time'],drop_first=True)

In [ ]:
df_encoded.head()

,total_bill,tip,size,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,True,False,True,False,False,False,True,False,True,False
1,10.34,1.66,3,False,True,True,False,False,False,True,False,True,False
2,21.01,3.50,3,False,True,True,False,False,False,True,False,True,False
3,23.68,3.31,2,False,True,True,False,False,False,True,False,True,False
4,24.59,3.61,4,True,False,True,False,False,False,True,False,True,False

In [ ]:
X=df_encoded.drop('tip',axis=1)
y=df_encoded['tip']

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=0)

In [ ]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_prd=model.predict(X_test)
y_prd

array([2.83765008, 2.99648634, 2.87347778, 1.49021209, 2.89139915,
       1.65620202, 2.56035166, 3.12085962, 2.85227104, 4.56674215,
       3.24712416, 3.23259474, 2.37367565, 2.19287908, 2.62051366,
       4.28155239, 1.87080356, 2.30559266, 2.56749843, 3.30065798,
       3.88084233, 2.95179082, 2.46144792, 2.46312363, 2.23183402])

In [ ]:
y_test

64     2.64
63     3.76
55     3.51
111    1.00
225    2.50
92     1.00
76     3.08
181    5.65
188    3.50
180    3.68
73     5.00
107    4.29
150    2.50
198    2.00
224    1.58
44     5.60
145    1.50
110    3.00
243    3.00
189    4.00
210    2.00
104    4.08
138    2.00
8      1.96
199    2.00
Name: tip, dtype: float64

In [ ]:
y_prd

array([2.83765008, 2.99648634, 2.87347778, 1.49021209, 2.89139915,
       1.65620202, 2.56035166, 3.12085962, 2.85227104, 4.56674215,
       3.24712416, 3.23259474, 2.37367565, 2.19287908, 2.62051366,
       4.28155239, 1.87080356, 2.30559266, 2.56749843, 3.30065798,
       3.88084233, 2.95179082, 2.46144792, 2.46312363, 2.23183402])

In [ ]:
from sklearn.metrics import r2_score
result= r2_score(y_test,y_prd)
print(result)

0.4309374445913341